name: app_p_70
description: A new Flutter project.
version: 1.0.0+1

environment: 
  sdk: '>=3.2.2 <4.0.0'
  
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  notification_permissions: ^0.6.1
  intl: ^0.19.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.11
  
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Architects Daughter
      fonts: 
        - asset: assets/fonts/ArchitectsDaughterRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
    - family: Kharkiv Tone
      fonts: 
        - asset: assets/fonts/KharkivToneRegular.ttf
          weight: 400
